import Logos

#print axioms Logos.valid_box_of_valid
#print axioms Logos.valid_K
#print axioms Logos.valid_T
#print axioms Logos.valid_B
#print axioms Logos.valid_4
#print axioms Logos.valid_5

#print axioms Logos.not_valid_of_pointed

#print axioms Logos.FiniteCountermodels.deadEndFinite
#print axioms Logos.FiniteCountermodels.deadEnd_not_reflexive
#print axioms Logos.FiniteCountermodels.deadEnd_symmetric
#print axioms Logos.FiniteCountermodels.deadEnd_transitive
#print axioms Logos.FiniteCountermodels.deadEnd_euclidean
#print axioms Logos.FiniteCountermodels.deadEnd_not_serial
#print axioms Logos.FiniteCountermodels.deadEnd_T_countermodel
#print axioms Logos.FiniteCountermodels.deadEnd_refutes_T

#print axioms Logos.FiniteCountermodels.arrowFinite
#print axioms Logos.FiniteCountermodels.arrow_reflexive
#print axioms Logos.FiniteCountermodels.arrow_transitive
#print axioms Logos.FiniteCountermodels.arrow_serial
#print axioms Logos.FiniteCountermodels.arrow_not_symmetric
#print axioms Logos.FiniteCountermodels.arrow_not_euclidean
#print axioms Logos.FiniteCountermodels.arrow_B_countermodel
#print axioms Logos.FiniteCountermodels.arrow_refutes_B

#print axioms Logos.FiniteCountermodels.pathFinite
#print axioms Logos.FiniteCountermodels.path_reflexive
#print axioms Logos.FiniteCountermodels.path_symmetric
#print axioms Logos.FiniteCountermodels.path_serial
#print axioms Logos.FiniteCountermodels.path_not_transitive
#print axioms Logos.FiniteCountermodels.path_not_euclidean
#print axioms Logos.FiniteCountermodels.path_4_countermodel
#print axioms Logos.FiniteCountermodels.path_refutes_4
#print axioms Logos.FiniteCountermodels.path_5_countermodel
#print axioms Logos.FiniteCountermodels.path_refutes_5
#print axioms Logos.FiniteCountermodels.path_has_contingency

#print axioms Logos.Grounding.actual_of_actualGrounds
#print axioms Logos.Grounding.ancestor_eq_of_ungrounded_target
#print axioms Logos.Grounding.exists_ungrounded_ancestor_of_acc
#print axioms Logos.Grounding.exists_ungrounded_ancestor
#print axioms Logos.Grounding.exists_ungrounded
#print axioms Logos.Grounding.ungrounded_unique
#print axioms Logos.Grounding.exists_unique_ungrounded
#print axioms Logos.Grounding.ungrounded_ancestor_all
#print axioms Logos.Grounding.ungrounded_ultimately_grounds_other
#print axioms Logos.Grounding.actual_is_possible_of_reflexive
#print axioms Logos.Grounding.actual_is_possible
#print axioms Logos.Grounding.possible_nonexistence_of_not_necessary
#print axioms Logos.Grounding.nonNecessary_is_derived
#print axioms Logos.Grounding.contingent_is_derived_of_nonNecessary
#print axioms Logos.Grounding.a4_iff_nonNecessary_is_derived
#print axioms Logos.Grounding.ungrounded_is_necessary
#print axioms Logos.Grounding.exists_necessary_ungrounded
#print axioms Logos.Grounding.ungrounded_not_created
#print axioms Logos.Grounding.exists_unique_absoluteGround
#print axioms Logos.Grounding.absoluteGround_is_necessarilyAseitic
#print axioms Logos.Grounding.exists_unique_necessarilyAseitic_absoluteGround

#print axioms Logos.Grounding.regress_totality_necessary_or_external_ground
#print axioms Logos.Grounding.external_totality_ground_is_necessary
#print axioms Logos.Grounding.contingent_totality_forces_necessary_reality
#print axioms Logos.Grounding.no_pure_contingent_reality

#print axioms Logos.GroundingModels.free_grounding_wellFounded
#print axioms Logos.GroundingModels.freeCreationAxioms
#print axioms Logos.GroundingModels.free_ground_is_absolute
#print axioms Logos.GroundingModels.free_creature_actual
#print axioms Logos.GroundingModels.free_creature_not_necessary
#print axioms Logos.GroundingModels.free_creature_contingent
#print axioms Logos.GroundingModels.free_creation_refutes_actual_implies_necessary
#print axioms Logos.GroundingModels.free_model_has_unique_absoluteGround

#print axioms Logos.GroundingModels.Independence.cycle_no_ungrounded
#print axioms Logos.GroundingModels.Independence.cycle_common_ground
#print axioms Logos.GroundingModels.Independence.cycle_not_wellFounded
#print axioms Logos.GroundingModels.Independence.twoRoot_wellFounded
#print axioms Logos.GroundingModels.Independence.twoRoot_a_ungrounded
#print axioms Logos.GroundingModels.Independence.twoRoot_b_ungrounded
#print axioms Logos.GroundingModels.Independence.twoRoot_common_ground_fails
#print axioms Logos.GroundingModels.Independence.bruteStructuralAxioms
#print axioms Logos.GroundingModels.Independence.brute_ungrounded
#print axioms Logos.GroundingModels.Independence.brute_contingent
#print axioms Logos.GroundingModels.Independence.brute_not_necessary
#print axioms Logos.GroundingModels.Independence.brute_A4_fails
#print axioms Logos.GroundingModels.Independence.createdRootNecessaryAxioms
#print axioms Logos.GroundingModels.Independence.createdRoot_ungrounded
#print axioms Logos.GroundingModels.Independence.createdRoot_A6_fails
#print axioms Logos.GroundingModels.Independence.accidentalCreationAxioms
#print axioms Logos.GroundingModels.Independence.accidental_ground_absolute
#print axioms Logos.GroundingModels.Independence.accidental_ground_not_necessarilyAseitic
#print axioms Logos.GroundingModels.Independence.accidental_A8_fails

#print axioms Logos.GroundingModels.InfiniteRegress.tower_step
#print axioms Logos.GroundingModels.InfiniteRegress.regress_derived
#print axioms Logos.GroundingModels.InfiniteRegress.regress_no_ungrounded
#print axioms Logos.GroundingModels.InfiniteRegress.regress_reverse_wellFounded
#print axioms Logos.GroundingModels.InfiniteRegress.regress_common_ground
#print axioms Logos.GroundingModels.InfiniteRegress.regress_contingent_is_derived
#print axioms Logos.GroundingModels.InfiniteRegress.regress_not_wellFounded

#print axioms Logos.GroundingModels.MinimalNecessity.twoRootNecessaryExistenceAxioms
#print axioms Logos.GroundingModels.MinimalNecessity.twoRoot_minimal_necessity_holds
#print axioms Logos.GroundingModels.MinimalNecessity.twoRoot_a_necessary
#print axioms Logos.GroundingModels.MinimalNecessity.twoRoot_b_necessary
#print axioms Logos.GroundingModels.MinimalNecessity.twoRoot_two_necessary_ungrounded
#print axioms Logos.GroundingModels.MinimalNecessity.brute_A4Prime_fails
#print axioms Logos.GroundingModels.MinimalNecessity.brute_A4_iff_A4Prime

#print axioms Logos.GroundingModels.TotalityRegress.regress_step
#print axioms Logos.GroundingModels.TotalityRegress.completeTotalityAxioms
#print axioms Logos.GroundingModels.TotalityRegress.totality_not_necessary
#print axioms Logos.GroundingModels.TotalityRegress.positive_totality_forces_external_necessary_ground
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.iRegressStep
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.iFactAxioms
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.internal_totality_not_necessary
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.every_internal_entity_nonNecessary
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.externality_fails
#print axioms Logos.GroundingModels.TotalityRegress.InternalGround.pure_contingency_survives_without_externality

#print axioms Logos.GroundingModels.TotalityRegressIndependence.IncompleteCoverage.externalAxioms
#print axioms Logos.GroundingModels.TotalityRegressIndependence.IncompleteCoverage.external_nonNecessary
#print axioms Logos.GroundingModels.TotalityRegressIndependence.IncompleteCoverage.completeness_fails
#print axioms Logos.GroundingModels.TotalityRegressIndependence.IncompleteCoverage.pure_contingency_survives_without_completeness
#print axioms Logos.GroundingModels.TotalityRegressIndependence.NoFactSufficientGround.totality_not_derived
#print axioms Logos.GroundingModels.TotalityRegressIndependence.NoFactSufficientGround.completeness_holds
#print axioms Logos.GroundingModels.TotalityRegressIndependence.NoFactSufficientGround.externality_holds
#print axioms Logos.GroundingModels.TotalityRegressIndependence.NoFactSufficientGround.fact_A4Prime_fails
#print axioms Logos.GroundingModels.TotalityRegressIndependence.NoFactSufficientGround.pure_contingency_survives_without_fact_A4Prime
