import Logos

#print axioms Logos.Grounding.contingentAbsolute_is_explanatorilyAbsolute
#print axioms Logos.Grounding.not_localFactSufficientExplanation_iff_contingentAbsolute
#print axioms Logos.Grounding.totality_explainer_is_necessary_from_core
#print axioms Logos.Grounding.local_totality_sufficient_explanation_forces_necessary_reality
#print axioms Logos.Grounding.totality_necessary_or_necessary_explainer_or_contingent_absolute
#print axioms Logos.Grounding.pure_contingency_forces_contingent_explanatory_absolute
#print axioms Logos.Grounding.localTotalityEF4_iff_no_contingent_absolute

#print axioms Logos.GroundingModels.FactSufficientExplanation.LocalNotGlobal.global_fact_EF4_fails
#print axioms Logos.GroundingModels.FactSufficientExplanation.LocalNotGlobal.localCore
#print axioms Logos.GroundingModels.FactSufficientExplanation.LocalNotGlobal.local_totality_EF4_holds
#print axioms Logos.GroundingModels.FactSufficientExplanation.LocalNotGlobal.necessary_reality_survives_global_EF4_failure

#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.bruteCore
#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.totality_notExplained
#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.contingent_explanatory_absolute_totality
#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.local_totality_EF4_fails
#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.all_entities_nonNecessary
#print axioms Logos.GroundingModels.FactSufficientExplanation.BruteTotality.pure_contingency_relocates_ultimacy_to_totality_fact
