import Logos

#print axioms Logos.Grounding.contingentExplanationProper_iff_selfExcluded
#print axioms Logos.Grounding.globalIrreflexivity_implies_contingentExplanationProper
#print axioms Logos.Grounding.totality_explainer_is_necessary_of_contingent_propriety
#print axioms Logos.Grounding.contingent_totality_forces_necessary_reality_without_global_irreflexivity
#print axioms Logos.Grounding.no_pure_contingency_without_global_irreflexivity

#print axioms Logos.Grounding.adequateSelfExplanation_implies_necessary
#print axioms Logos.Grounding.adequateExplanation_of_contingentPropriety
#print axioms Logos.Grounding.totality_explainer_is_necessary_of_local_adequacy
#print axioms Logos.Grounding.contingent_totality_forces_necessary_reality_from_local_adequacy
#print axioms Logos.Grounding.no_pure_contingency_from_local_adequacy

#print axioms Logos.GroundingModels.SelfExplanation.NecessarySelfCitation.root_self_explains
#print axioms Logos.GroundingModels.SelfExplanation.NecessarySelfCitation.global_irreflexivity_fails
#print axioms Logos.GroundingModels.SelfExplanation.NecessarySelfCitation.contingent_explanation_proper
#print axioms Logos.GroundingModels.SelfExplanation.NecessarySelfCitation.contingentScopeAxioms
#print axioms Logos.GroundingModels.SelfExplanation.NecessarySelfCitation.necessary_reality_survives_necessary_self_explanation

#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.node0_nonNecessary
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.node0_self_explains
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.contingent_explanation_proper_fails
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.fact_sufficient_explanation_holds
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.totality_scope_holds
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.contingent_coverage_holds
#print axioms Logos.GroundingModels.SelfExplanation.ContingentSelfCitation.pure_contingency_survives_if_contingent_self_explanation_counts

#print axioms Logos.GroundingModels.SelfExplanationAdequacy.LocalOnly.node0_self_explains
#print axioms Logos.GroundingModels.SelfExplanationAdequacy.LocalOnly.global_contingent_propriety_fails
#print axioms Logos.GroundingModels.SelfExplanationAdequacy.LocalOnly.adequateScopeAxioms
#print axioms Logos.GroundingModels.SelfExplanationAdequacy.LocalOnly.necessary_reality_survives_global_contingent_self_citation
#print axioms Logos.GroundingModels.SelfExplanationAdequacy.NoLocalAdequacy.adequate_totality_scope_fails
#print axioms Logos.GroundingModels.SelfExplanationAdequacy.NoLocalAdequacy.pure_contingency_survives_when_self_citation_counts_as_adequate
