import Logos

#print axioms Logos.Grounding.genericExternality_implies_explanatoryExternality_of_bridge
#print axioms Logos.Grounding.explanatoryF4_implies_genericF4_of_bridge

#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.node0_constitutes
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.node0_not_explains
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.root_explains
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.root_not_constitutes
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.explanation_implies_grounding
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.old_externality_fails
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.explanatory_externality_holds
#print axioms Logos.GroundingModels.TotalityExternalityComparison.MixedRoles.bridged_externality_strictness_witness

#print axioms Logos.GroundingModels.TotalityExternalityComparison.EWithoutEExpl.generic_externality_holds
#print axioms Logos.GroundingModels.TotalityExternalityComparison.EWithoutEExpl.node0_explains
#print axioms Logos.GroundingModels.TotalityExternalityComparison.EWithoutEExpl.explanatory_externality_fails
#print axioms Logos.GroundingModels.TotalityExternalityComparison.EWithoutEExpl.explanation_implies_grounding_fails

#print axioms Logos.GroundingModels.TotalityExternalityComparison.F4NotEF4.explanation_implies_grounding
#print axioms Logos.GroundingModels.TotalityExternalityComparison.F4NotEF4.generic_F4_holds
#print axioms Logos.GroundingModels.TotalityExternalityComparison.F4NotEF4.explanatory_F4_fails
#print axioms Logos.GroundingModels.TotalityExternalityComparison.F4NotEF4.bridged_F4_not_EF4

#print axioms Logos.GroundingModels.TotalityExternalityComparison.EF4NotF4.explanatory_F4_holds
#print axioms Logos.GroundingModels.TotalityExternalityComparison.EF4NotF4.generic_F4_fails
#print axioms Logos.GroundingModels.TotalityExternalityComparison.EF4NotF4.explanation_implies_grounding_fails
